name: Lint

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: lts/gallium

      - name: Install yarn
        run: npm i -g yarn

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
